name: three-jobs-in-the-workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: i want ot build
        run: echo "building"
  Test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "testing it"

  deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: deploying
        run: echo "runing the deploy"

  finish:
    needs: deploy
    runs-on: macos-14
    steps:
      - name: last job
        run: echo "finishing the job"

  aws-job:
    needs: finish
    runs-on: ubuntu-latest
    steps:
      - name: aws job
        run: echo "running the aws job"