name: example
on: workflow_dispatch

jobs:
  my_greet:
    runs-on: ubuntu-latest
    steps:
      - name: greeting to mike
        run: echo "good evening michael"

  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: second job
        run: echo "this is my second job"
